# -*- coding: utf-8 -*-
"""bank-call-sentiment-analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3mrT4z2lHW3yQYHllfzekiyGJ7GyxkR

<h1 style="text-align:center;font-weight:bold;font-size:2em">BANK CALL SENTIMENT ANALYSIS</h1>
"""

!python -m spacy download en_core_web_md

"""# Import spaCy Libraries"""

import spacy
from spacy.matcher import Matcher
from spacy.tokens import Span
from spacy import displacy
import en_core_web_md

nlp = en_core_web_md.load()

"""# Sample statements for testing pattern recognition"""

df=[
    "Thank you for calling EFG Bank, your call is recorded, you are not required to give any SSN during the call.",
    "Thank you for calling FGH Bank, your call is recorded, you are required to give any Social Security Number during the call.",
    "Thank you for calling GHI Bank, your call is recorded, you are not required to give credit card number during the call.",
    "Thank you for calling ABC Bank, your call is recorded, you are not required to give any SSN or full credit card number during the call.",
    "Thank you for calling DEF Bank, your call is recorded, you are required to give any SSN or full credit card number during the call.",
    "Thank you for calling BCD Bank, your call is recorded, you are not required to give any Social Security Number or full credit card number during the call.",
    "Thank you for calling CDE Bank, your call is recorded, you are required to give any Social Security Number or full credit card number during the call."
]

"""# Defining patterns"""

pattern1= [{"LOWER":"bank"},{'OP' : '+'},{"LOWER" : "ssn"}]
pattern2= [{"LOWER":"bank"},{'OP' : '+'},{"LOWER" : "social"},{"LOWER" : "security"},{"LOWER" : "number"}]
pattern3= [{"LOWER":"bank"},{'OP' : '+'},{"LOWER" : "card"},{"LOWER" : "number"}]

matched_sents = []

"""# Callback funtion"""

def label_sentiment(matcher, doc,i ,matches):
    match_id, start, end = matches[i]
    string_id=doc.vocab.strings[match_id]
    span = doc[start:end]
    sent = span.sent
    label = ""

    if "not" in str(sent):
        label+="correct "+doc.vocab.strings[match_id]
    else:
        label+="faulty "+doc.vocab.strings[match_id]
        
    match_ents=[{
        'start' : span.start_char-sent.start_char,
        'end' : span.end_char-sent.start_char,
        'label' : label
    }]
    
    matched_sents.append({'text':sent.text,'ents':match_ents,'id':string_id})

"""# Creating an instance of matcher"""

matcher = Matcher(nlp.vocab)

"""# Adding patterns to matcher"""

matcher.add("Short name match",label_sentiment,pattern1)
matcher.add("Long name match",label_sentiment,pattern2)
matcher.add("Card match",label_sentiment,pattern3)

"""# Testing matcher with various text inputs"""

doc =  nlp(df[0])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is not asked to provide SSN number</b>"""

matched_sents = []

doc =  nlp(df[1])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is asked to provide SSN number</b>"""

matched_sents = []

doc =  nlp(df[2])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is not asked to provide credit card number</b>"""

matched_sents = []

doc =  nlp(df[3])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is not asked to provide SSN number as well as credit card number</b>"""

matched_sents = []

doc =  nlp(df[4])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is asked to provide SSN number as well as credit card number</b>"""

matched_sents = []

doc =  nlp(df[5])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is not asked to provide SSN number as well as credit card number</b>"""

matched_sents = []

doc =  nlp(df[6])

matches= matcher(doc)

displacy.render(matched_sents, style ='ent', manual =True)

"""<b>Listerner is asked to provide SSN number as well as credit card number</b>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWDgteV-sNXVRkc0xwyodmJt18ImebZ1UcKA&usqp=CAU">
"""